//Exception Handeling 

//try ,throw,catch

// try{
// let x = 1;
// if(x == 0)
// console.log('THis is try block...!');
// throw('error detacted..!');
// }
// catch(err){
//     console.log(err);
// }
// finally{
//     console.log("this is finally block this will defenetly run...!");
    
// }


//setTimtout & setIntervel

//setTimtout

console.log('this is Syncronus code');

setTimeout(()=>{
    console.log("this is SetTimeout");

},4000);

// setInterval

// setInterval(()=>{
// console.log("this is setINtervel");

// },2000);
